spring:
  application:
    name: gateway

  main:
    web-application-type: reactive

server:
  port: 8000

jwt:
  secret:
  token-prefix: Bearer
filter:
  exclude:
    path: /api/auth/login,/api/user/register,/api/auth/reissue

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka,http://admin:1234@localhost:8762/eureka
  instance:
    prefer-ip-address: true
